// web/testi/it.mjs — tutte le scritte dell'interfaccia
export const T = {
  titolo: 'Analisi vocale',
  sottotitolo: 'Confronta due registrazioni della stessa voce. L\'audio resta sul tuo computer.',
  entra: 'Entra con Google',
  esci: 'Esci',
  perche: 'Serve un accesso per sapere come viene usato lo strumento e migliorarlo. Non registriamo l\'audio.',
  caricaPre: 'Trascina qui la registrazione PRE (o clicca)',
  caricaPost: 'Trascina qui la registrazione POST (o clicca)',
  stereo: 'Questo file ha due canali. È una registrazione con PRE a sinistra e POST a destra?',
  stereoSi: 'Sì: sinistra PRE, destra POST', stereoNo: 'No: è un normale file stereo',
  calcolo: 'Praat sta calcolando lo spettrogramma…',
  primaVolta: 'La prima volta si scarica Praat (circa 25 MB): un momento.',
  lettura: 'Lettura di ',
  altroFile: 'Ora carica anche l\'altra registrazione.',
  caricaAncora: (lato) => `Ora carica anche la registrazione ${lato}.`,
  dueCanali: (lato) => `${lato}: file a due canali, analizzato come stereo (media dei canali).`,
  selezionaPrima: 'Seleziona prima un tratto trascinando sullo spettrogramma.',
  misurando: 'Praat sta misurando il tratto…',
  play: '▶ Play', pausa: '❚❚ Pausa', ab: 'In ascolto: ', prePoiPost: 'Ascolta PRE poi POST', togli: 'Togli selezione',
  misura: 'Misura il tratto', esporta: 'Scarica immagine (PNG)',
  pareggio: 'Volume pareggiato (solo per l\'ascolto: non cambia le misure)',
  vocemaschile: 'Voce maschile (formanti fino a 5000 Hz)',
  f0: 'Altezza (F0)', formanti: 'Formanti', fascia: 'Fascia 4-5 kHz',
  aiutoComandi: 'Clic = salta · trascina = seleziona un tratto (si ripete) · pizzico o Ctrl + rotella = zoom · Maiusc + rotella = sposta · Spazio = play/pausa · X = PRE/POST · Esc = togli selezione',
  legendaParti: { grigio: 'Grigio: armoniche e rumore', f0: 'linea fucsia: altezza (F0), scala a destra', formanti: 'puntini: formanti F1 arancio, F2 verde, F3 blu, F4 rosa', fascia: 'fascia gialla: 4-5 kHz' },
  // «CPPS Robust» solo se la figura accompagna una tabella di misure; il tetto delle formanti solo se diverso dal solito
  piede: (versione, { maschile = false, misure = false } = {}) =>
    `Analisi con Praat ${versione} (Boersma & Weenink) nel browser` + (misure ? ' · CPPS Robust' : '') + (maschile ? ' · formanti fino a 5000 Hz' : '') + ' · stageplot.it/voce',
  didattico: 'Strumento didattico: confronta la persona con sé stessa. Non è uno strumento diagnostico.',
  lungo: 'File lungo (oltre 10 minuti): il calcolo può richiedere qualche minuto.',
  acuto: 'Nota acuta: le formanti sono poco affidabili (l\'altezza si avvicina alla prima formante).',
  tratto: 'tratto',
  titoloFigura: 'Titolo della figura',
  titoloPredefinito: (sel) => 'Confronto PRE / POST' + (sel || ''),
  zoomPiu: 'Zoom +', zoomMeno: 'Zoom −', vediTutto: 'Vedi tutto',
  differenza: 'Differenza (POST − PRE)',
  decodificato: 'M4A/OGG: il browser lo converte a 44,1 kHz prima dell\'analisi. Per i numeri della tesi usa WAV, AIFF o FLAC.',
  oltreFine: 'Il tratto scelto è oltre la fine di questa registrazione.',
  finisce: (lato, t) => `Il ${lato} finisce a ${t}: misurato fino lì.`,
  silenziosa: 'Registrazione silenziosa',
  troppoLungo: 'File troppo lungo: tagliane una parte di al massimo 30 minuti.',
  prepNonRiuscita: 'Non riesco a preparare Praat: controlla la connessione e ricarica la pagina.',
  fileNonAnalizzato: 'Praat non è riuscito ad analizzare questo file.',
  attendiCalcolo: 'Praat sta ancora calcolando: aspetta qualche secondo e riprova.',
  figuraNonRiuscita: 'Non sono riuscito a creare l\'immagine: riprova.',
  fonti: 'Da dove viene ogni misura', sorgente: 'Codice sorgente (GPL-3)',
  nonIncorporabile: 'Apri Analisi vocale in una scheda sua: '
}
